theme: jekyll-theme-minimal
title: Mapping Ithaca's Queer History
description: This website provides information on places in and around Ithaca that have been important to queer communities here. 
logo: LGBT_rainbow_flag.png
