theme: jekyll-theme-minimal
title: Mapping Cornell's Queer History
description: This website provides information on places at Cornell University that have been important to queer communities here. 

Morrie's Bar
Gay People's Center
Student Homophile League
Gay Liberation Front
Gay People at Cornell (GayPAC)
Loving House
Gay, Bisexuals, and Lesbians of Color (GBLOC)
First GBLOC conference
May Gay Festival
Human Sexuality Collection
Barbara Gittings Speaks at Cornell
Lesbian/Bisexual Women Support Group
