theme: jekyll-theme-minimal
title: Mapping Cornell's Queer History
description: This website provides information on places at Cornell University that have been important to queer communities here. 

